//
//  SupplementData.swift
//  Riverhead NY Budget App
//
//  Loads the bundled Budget Supplement datasets (generated by the shared ETL,
//  etl/parse_budget_supplement.py) from the app bundle:
//   • reductions.json          — itemized, confidence-tagged 2027 reduction
//                                candidates (controllable lines over their run-rate)
//   • supplement-outliers.json — data-driven budget-accuracy outliers
//   • supplement-lines.json    — the full classified per-account ledger
//
//  These are the single source of truth shared across the iOS, web, and Android
//  apps; nothing here re-derives or hard-codes the figures.
//

import Foundation

// MARK: - Reductions

struct SupplementReduction: Identifiable, Decodable, Hashable {
    let account: String
    let name: String
    let fund: String
    let fundName: String
    let actual2024: Double?
    let ytd2025: Double?
    let tentative2026: Double?
    let target: Double
    let confidence: String   // "firm" | "moderate" | "volatile"

    var id: String { account }
}

struct SupplementReductionsFile: Decodable {
    let gapToClose: Double
    let total: Double
    let byConfidence: [String: Double]
    let items: [SupplementReduction]
    let method: String
}

// MARK: - Outliers

struct SupplementOutlier: Identifiable, Decodable, Hashable {
    let account: String
    let fund: String
    let name: String
    let control: String
    let actual2024: Double?
    let budget2025: Double?
    let ytd2025: Double?
    let tentative2026: Double?
    let flag: String
    let excess: Double

    var id: String { "\(flag)-\(account)" }
}

struct SupplementOutliersFile: Decodable {
    let overBudget: [SupplementOutlier]
    let chronicOverrun: [SupplementOutlier]
    let noBudget: [SupplementOutlier]
    let recoverablePoolControllable: Double
    let note: String
}

// MARK: - Line items

struct SupplementLine: Identifiable, Decodable, Hashable {
    let account: String
    let fund: String
    let name: String
    let kind: String       // "expenditure" | "revenue"
    let control: String    // "mandated" | "personnel" | "controllable" | "revenue"
    let actual2024: Double?
    let budget2025: Double?
    let ytd2025: Double?
    let request2026: Double?
    let tentative2026: Double?
    let actual2023: Double?
    let budget2024: Double?
    let ytd2024: Double?
    let tentative2025: Double?
    let overBudget2026: Double?

    var id: String { account }
}

private struct SupplementLinesFile: Decodable { let lines: [SupplementLine] }

// MARK: - Loader

enum SupplementData {
    static let reductions: SupplementReductionsFile? = load("reductions")
    static let outliers: SupplementOutliersFile? = load("supplement-outliers")
    static let lines: [SupplementLine] = (load("supplement-lines") as SupplementLinesFile?)?.lines ?? []

    private static func load<T: Decodable>(_ resource: String) -> T? {
        guard let url = Bundle.main.url(forResource: resource, withExtension: "json"),
              let data = try? Data(contentsOf: url) else { return nil }
        return try? JSONDecoder().decode(T.self, from: data)
    }
}
